modLoader="kotlinforforge"
loaderVersion="[4,)"

issueTrackerURL="https://github.com/SirEdvin/Peripheralium/issues"
logoFile="pack.png"

license="MIT"

[[mods]]
modId="peripheralium"
version="${file.jarVersion}"
displayName="Peripheralium"
displayURL="https://github.com/SirEdvin/Peripheralium"

credits=""
authors=""
description='''
'''

[[dependencies.peripheralium]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},47)"
ordering="NONE"
side="BOTH"

[[dependencies.peripheralium]]
modId="computercraft"
mandatory=true
versionRange="[${computercraftVersion},)"
ordering="NONE"
side="BOTH"